
server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/dbmovie?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username : root
    password : 123456
    driverClassName : com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:D:\前端资料\MovieApi\imgs
mybatis:
  type-aliases-package: com.example.movies.pojo
  mapper-locations: classpath:mapper/*.xml